### ISSUE TITLE
OpenGraph.ParseUrl throws NullReferenceException

### ISSUE THREAD

**Issue by kbednars** [ghorsey/OpenGraph-Net#29] opened 2021-03-30 07:05 UTC
Hello!
I've encountered a problem with the method `ParseUrl`. When I provide a URL, which leads to a not existing server, for which web browser would show `This site can't be reached`, `ParseUrl` method throw `NullReferenceException` with message `Object reference not set to an instance of an object`.

**Expected behavior**
In my opinion, the expected behavior is to maybe throw `HttpRequestException` with the message `Response status code does not indicate success: 400 (Bad Request).`, because with `NullReferenceException` there is no information what happened inside when parsing URL.

**Desktop (please complete the following information)**
OS: macOS
.Net 5.0
Version : `<PackageReference Include="OpenGraph-Net" Version="3.2.6" />`

**Comment by ghorsey** [comment] 2021-06-08 03:17
@kbednars  thank you for this report.  I'm surprised I never caught this myself.  I dislike `NullReferenceException`.

**Comment by ghorsey** [comment] 2021-06-08 05:34
@kbednars I haven't been able to recreate this.

I created four unit tests to validate this behavior:

* TestParsingA404UrlAsync
* TestParsingA404Url
* TestParsingABadHostAsync
* TestParsingABadHost

And on each run, the call to `ParseUrl` or `ParseUrlAsync` all throw a `WebException`.

See the tests here:
https://github.com/ghorsey/OpenGraph-Net/blob/77fe0365ef2c4c0d88114eff9a2290385f498872/tests/OpenGraphNet.Tests/OpenGraphTests.cs#L565 

So I'm cannot recreate the issue as you've described it.

**Comment by kbednars** [comment] 2021-06-08 06:21
What happens, if for example  you provide such url `"https://www.developors.facebook.com/"`?

**Comment by ghorsey** [comment] 2021-06-08 06:27
It passed on my local.

I just updated the unit test to use your URL, and according to the test, a `WebException` is thrown.

See https://github.com/ghorsey/OpenGraph-Net/blob/de69c8498d1925ee6faacdd17286c0e654ccc2c6/tests/OpenGraphNet.Tests/OpenGraphTests.cs#L584

And this is the job that is passing the updated UT.
https://github.com/ghorsey/OpenGraph-Net/actions/runs/917323574

**Comment by kbednars** [comment] 2021-06-08 07:25
In `HttpDownloader.cs` in method `GetPageAsync()` the moment 
`((HttpWebResponse)ex.Response).StatusCode  == HttpStatusCode.MovedPermanently`
causes issue in my project, because when WebException occur Response is null and here we trying to access this value. When I change to 
`((HttpWebResponse)ex.Response)?.StatusCode  == HttpStatusCode.MovedPermanently` 
it seems to work fine.

**Comment by ghorsey** [comment] 2021-06-08 07:52
Hmm... I believe you. 

I just wonder why I cannot recreate the behavior with a unit test.  it hurts me a little inside. lol.

Anyway, I made the modification to use the Elvis operator on the status code check.

There is a pre-release version that should have just published:
 * Version: [3.2.7-alpha.0.40](https://www.nuget.org/packages/OpenGraph-Net/3.2.7-alpha.0.40). 

Can you pull the pre-release and confirm the issue is resolved in your project?

If that fixes it for you, I'll tag an official version 3.2.7 for publication tomorrow.

It's late for me now and I need my beauty sleep :) 

Thanks for raising this issue!

**Comment by kbednars** [comment] 2021-06-08 08:07
Not it works fine, thanks :)

**Comment by ghorsey** [comment] 2021-06-08 17:33
I'm assuming you meant to say "Now it works..." :) 

I triggered a build for v3.2.7, which should go live today on NuGet.

**Closed by ghorsey** 2021-06-08 17:33 UTC
Labels: bug
